### ISSUE TITLE
Remove Obsolete Census Support

### ISSUE THREAD

**Issue by Rijam** [PotatoPersonThing/CalValEX#55]
As of 1.4.4, Mod Calls to Census are no longer necessary. Instead, Census will automatically get the spawn condition for the Town NPC by a localization key.

Including the old Mod Calls to Census will produce a warning and error in the client.log for each call.

```
[15:21:31.997] [Main Thread/WARN] [tML]: Silently Caught Exception: 
System.Exception: Call Error: The 2nd parameter of TownNPCCondition is now LocalizedText and is optional. Also, localization is now automatic, keys will appear in your hjson files. This TownNPCCondition Mod.Call is only needed if using LocalizedText.WithFormatArgs
   at Census.CensusSystem.Call(Object[] args) in CensusSystem.cs:line 520
   at CalValEX.CalValEX.PostSetupContent() in CalValEX.cs:line 165
   at Terraria.ModLoader.ModContent.<>c.<Load>b__44_2(Mod mod) in tModLoader\Terraria\ModLoader\ModContent.cs:line 333
   at Terraria.ModLoader.ModContent.LoadModContent(CancellationToken token, Action`1 loadAction) in tModLoader\Terraria\ModLoader\ModContent.cs:line 408
   at Terraria.ModLoader.ModContent.Load(CancellationToken token) in tModLoader\Terraria\ModLoader\ModContent.cs:line 332
   at Terraria.ModLoader.ModLoader.Load(CancellationToken token) in tModLoader\Terraria\ModLoader\ModLoader.cs:line 131
   at Terraria.ModLoader.ModLoader.Reload() in tModLoader\Terraria\ModLoader\ModLoader.cs:line 220
   at Terraria.Main.DedServ() in tModLoader\Terraria\Main.cs:line 4611
   at Terraria.Program.RunGame() in tModLoader\Terraria\Program.cs:line 264
   at Terraria.Program.LaunchGame_(Boolean isServer) in tModLoader\Terraria\Program.cs:line 240
   at Terraria.Program.LaunchGame(String[] args, Boolean monoArgs) in tModLoader\Terraria\Program.cs:line 213
   at Terraria.MonoLaunch.Main_End(String[] args) in tModLoader\Terraria\MonoLaunch.cs:line 79
   at Terraria.MonoLaunch.<>c__DisplayClass1_0.<Main>b__1() in tModLoader\Terraria\MonoLaunch.cs:line 65

[15:21:31.997] [Main Thread/ERROR] [Census]: Census Call Error:    at Census.CensusSystem.Call(Object[] args) in CensusSystem.cs:line 520Call Error: The 2nd parameter of TownNPCCondition is now LocalizedText and is optional. Also, localization is now automatic, keys will appear in your hjson files. This TownNPCCondition Mod.Call is only needed if using LocalizedText.WithFormatArgs
```

The localization keys for Census are already included in this mod*
https://github.com/PotatoPersonThing/CalValEX/blob/afb6335a59a08a0b5853297c0a4292f6b60aeb3c/Localization/en-US.hjson#L76
So, all that needs to be done is to remove the Mod Calls from PostSetupContent
https://github.com/PotatoPersonThing/CalValEX/blob/afb6335a59a08a0b5853297c0a4292f6b60aeb3c/CalValEX.cs#L165

(*Most of the Nugget and Slime Town Pets need the values for their spawn condition keys to be updated.)

**Comment by GinYuH** [comment]
fixed
